import { ArrowDown, ArrowRight, Bot, CheckCircle2, Database, FileSpreadsheet, GitBranch, Globe2, HardDrive, Link2, SearchCheck, ShieldCheck, Sparkles, UserCheck } from "lucide-react";
import { createElement, useEffect, useState } from "react";
import { localDataApi } from "../utils/localDataApi.js";

const SOURCES = [
  [FileSpreadsheet, "bg-blue-50 text-blue-700 ring-blue-200", "Raw parts CSVs", "BMW Raw scrape, Honda Parts House, Harley-Davidson and Partmaster raw data", "OEM numbers when present, descriptions, diagram categories, years, models, prices, quantities and saved source URLs.", "Source observations—not automatically trusted master records."],
  [Database, "bg-emerald-50 text-emerald-700 ring-emerald-200", "Vehicle identity references", "MPSOV.csv and Vehicle Mapping ePID.xlsx with VCDB, ARI and NADA aliases", "Maps ePID or a unique year/make/model to canonical vehicle identity, trim, vehicle type and motorcycle type.", "MPSOV enriches vehicle fitment; it is not a source of OEM part numbers."],
  [Globe2, "bg-cyan-50 text-cyan-700 ring-cyan-200", "Linked supplier evidence", "Saved catalog URLs, HondaPartsHouse where-used pages, MAX BMW fiche and compatible structured supplier pages", "Confirms exact OEM numbers and descriptions, and can discover many parts or fitments from one shared page.", "The worker follows URLs connected to the data and respects the page budget; it does not blindly crawl the web."],
  [Bot, "bg-violet-50 text-violet-700 ring-violet-200", "AI-assisted research", "The Analyze parts workflow creates a focused prompt for GPT or another research-capable AI", "Helps interpret messy catalog text, identify likely OEM numbers and explain left/right or variant differences.", "AI results return as proposals and must carry evidence or receive human review."],
  [UserCheck, "bg-amber-50 text-amber-700 ring-amber-200", "Human decisions", "Evidence review, bulk approval, correction and rejection inside Partmaster", "Resolves uncertainty, checks variant details and decides what is safe to promote into trusted master data.", "A person remains the final authority for ambiguous or conflicting records."],
  [GitBranch, "bg-slate-100 text-slate-700 ring-slate-200", "GitHub workspace", "Application code plus lightweight input, review, analysis and approved-data files", "Lets the team share the interface and reviewed results without uploading huge local datasets.", "Large CSVs, DuckDB and generated master exports stay on the Mac."],
];

const STEPS = [
  ["1", "Inventory and ingest", "Find every parts CSV in local_data/inbox or inbox/rawdata, flag unprocessed files, and keep each original row and URL traceable."],
  ["2", "Normalize", "Standardize manufacturers and OEM numbers so punctuation does not create false differences."],
  ["3", "Deduplicate", "Build one identity per manufacturer + normalized OEM number while preserving source occurrences."],
  ["4", "Understand", "Classify the family and extract category-aware facts such as side, dimensions, material or equipment."],
  ["5", "Map and verify", "Apply ePID mappings and check the highest-value linked supplier pages in controlled batches."],
  ["6", "Measure, review and publish", "Compare raw sources with master completion, auto-accept only strong evidence, send uncertainty to a person, and export with provenance."],
];

const FIELDS = ["Normalized OEM identity", "Description", "Part family", "Component scope", "Side and position", "Dimensions and specifications", "Material, color and finish", "Mirror/electrical equipment", "Vehicle ePID and trim", "Fitment and assembly", "Aliases and relationships", "Evidence and confidence", "Duplicate counts", "Source traceability"];

function Metric({ label, value }) {
  return <div className="rounded-2xl border border-white/10 bg-white/[0.07] p-4"><p className="text-xs font-bold uppercase tracking-wide text-cyan-200">{label}</p><p className="mt-1 text-2xl font-black text-white">{Number(value || 0).toLocaleString()}</p></div>;
}

function DiagramNode({ Icon, eyebrow, title, detail, tone = "border-slate-200 bg-white text-slate-700" }) {
  return <article className={`min-w-0 rounded-2xl border p-4 shadow-sm ${tone}`}><div className="flex items-start gap-3"><span className="grid h-9 w-9 shrink-0 place-items-center rounded-xl bg-white/80 shadow-sm ring-1 ring-black/5">{createElement(Icon, { size: 18, "aria-hidden": true })}</span><div className="min-w-0"><p className="text-[10px] font-black uppercase tracking-[0.14em] opacity-70">{eyebrow}</p><h4 className="mt-1 text-sm font-black">{title}</h4><p className="mt-1 text-xs leading-5 opacity-80">{detail}</p></div></div></article>;
}

function FlowArrow() {
  return <span className="grid place-items-center text-slate-300" aria-hidden="true"><ArrowDown className="md:hidden" size={20} /><ArrowRight className="hidden md:block" size={20} /></span>;
}

function SystemSchematic() {
  return <section className="overflow-hidden rounded-3xl border border-slate-200 bg-white shadow-panel"><header className="border-b border-slate-200 bg-gradient-to-r from-slate-950 via-blue-950 to-cyan-950 px-5 py-6 text-white sm:px-7"><p className="text-xs font-black uppercase tracking-[0.18em] text-cyan-300">System schematic</p><h3 className="mt-2 text-2xl font-black">How Partmaster moves data from scrape to trusted master</h3><p className="mt-2 max-w-3xl text-sm leading-6 text-slate-300">Arrows show data flow. Every uncertain value keeps its evidence and can be routed to a person instead of being silently accepted.</p></header><div className="space-y-5 p-5 sm:p-7">
    <div><p className="mb-3 text-xs font-black uppercase tracking-wide text-slate-500">1 · Inputs</p><div className="grid gap-3 md:grid-cols-3"><DiagramNode Icon={FileSpreadsheet} eyebrow="Private local files" title="Raw scrape CSVs" detail="OEM numbers, descriptions, vehicles, diagrams, prices, quantities and saved URLs." tone="border-blue-200 bg-blue-50 text-blue-950" /><DiagramNode Icon={Database} eyebrow="Local references" title="Vehicle identity data" detail="MPSOV and ePID mappings connect source vehicles to normalized makes, models, trims and types." tone="border-emerald-200 bg-emerald-50 text-emerald-950" /><DiagramNode Icon={Globe2} eyebrow="Controlled network" title="Linked supplier pages" detail="Only saved or part-specific catalog pages are checked, within the selected source-page budget." tone="border-cyan-200 bg-cyan-50 text-cyan-950" /></div></div>
    <div className="grid place-items-center text-blue-400" aria-hidden="true"><ArrowDown size={23} /></div>
    <div className="rounded-3xl border-2 border-dashed border-blue-200 bg-blue-50/40 p-4 sm:p-5"><div className="mb-4 flex flex-wrap items-center justify-between gap-2"><div><p className="flex items-center gap-2 text-xs font-black uppercase tracking-wide text-blue-700"><HardDrive size={15} />Private local processing on this Mac</p><p className="mt-1 text-xs text-slate-500">DuckDB processes large sources in low-memory chunks; raw rows never need to be uploaded.</p></div><span className="rounded-full bg-blue-100 px-3 py-1 text-[10px] font-black uppercase text-blue-700">local_data stays private</span></div><div className="grid gap-2 md:grid-cols-[1fr_auto_1fr_auto_1fr_auto_1fr]"><DiagramNode Icon={SearchCheck} eyebrow="Inventory" title="Discover and import" detail="Find every raw CSV, count rows, and flag files that still need scanning." tone="border-blue-200 bg-white text-blue-950" /><FlowArrow /><DiagramNode Icon={Link2} eyebrow="Identity" title="Normalize and deduplicate" detail="Standardize make and OEM number, then preserve duplicates as traceable occurrences." tone="border-violet-200 bg-white text-violet-950" /><FlowArrow /><DiagramNode Icon={Bot} eyebrow="Enrichment" title="Classify, map and extract" detail="Add family, scope, fitment, side, dimensions and category-specific attributes when supported." tone="border-emerald-200 bg-white text-emerald-950" /><FlowArrow /><DiagramNode Icon={ShieldCheck} eyebrow="Evidence" title="Verify and score" detail="Compare sources, detect conflicts and assign confidence to each proposed value." tone="border-cyan-200 bg-white text-cyan-950" /></div></div>
    <div className="grid place-items-center text-violet-400" aria-hidden="true"><ArrowDown size={23} /></div>
    <div><p className="mb-3 text-xs font-black uppercase tracking-wide text-slate-500">2 · Quality decision</p><div className="grid gap-3 lg:grid-cols-[1fr_auto_1fr]"><div className="space-y-3"><DiagramNode Icon={CheckCircle2} eyebrow="Automatic route" title="Strong, non-conflicting evidence" detail="Values meeting the chosen confidence threshold can update master automatically." tone="border-emerald-200 bg-emerald-50 text-emerald-950" /><p className="rounded-xl bg-emerald-50 px-3 py-2 text-center text-[11px] font-bold text-emerald-700">High confidence → promote</p></div><div className="grid place-items-center"><span className="rounded-full bg-slate-100 px-3 py-1 text-[10px] font-black uppercase text-slate-500">or</span></div><div className="space-y-3"><DiagramNode Icon={UserCheck} eyebrow="Human route" title="Ambiguous or conflicting evidence" detail="A reviewer can approve, correct or reject the proposed identity, fitment or variant facts." tone="border-amber-200 bg-amber-50 text-amber-950" /><p className="rounded-xl bg-amber-50 px-3 py-2 text-center text-[11px] font-bold text-amber-800">Approve/edit → promote · Reject → hold outside master</p></div></div></div>
    <div className="grid place-items-center text-emerald-500" aria-hidden="true"><ArrowDown size={23} /></div>
    <div><p className="mb-3 text-xs font-black uppercase tracking-wide text-slate-500">3 · Trusted destination and consumers</p><DiagramNode Icon={Database} eyebrow="Canonical destination" title="Consolidated master data" detail="One manufacturer + normalized OEM identity with facts, applications, relationships, confidence and source traceability." tone="border-emerald-300 bg-emerald-100 text-emerald-950" /><div className="grid place-items-center text-emerald-500" aria-hidden="true"><ArrowDown size={23} /></div><div className="grid gap-3 md:grid-cols-2"><DiagramNode Icon={SearchCheck} eyebrow="Private detailed access" title="Local search, filters and exports" detail="Search hundreds of thousands of parts, inspect evidence and export master CSVs without moving the database." tone="border-blue-200 bg-blue-50 text-blue-950" /><DiagramNode Icon={GitBranch} eyebrow="Team-facing layer" title="GitHub Pages and Partout Pro" detail="GitHub receives lightweight aggregate metrics; approved master exports or an API can feed Partout Pro." tone="border-slate-300 bg-slate-100 text-slate-900" /></div></div>
    <div className="flex flex-wrap gap-2 border-t border-slate-200 pt-4 text-[11px] font-bold"><span className="rounded-full bg-blue-100 px-3 py-1.5 text-blue-800">Blue: private/local</span><span className="rounded-full bg-cyan-100 px-3 py-1.5 text-cyan-800">Cyan: controlled evidence check</span><span className="rounded-full bg-amber-100 px-3 py-1.5 text-amber-800">Amber: human decision</span><span className="rounded-full bg-slate-100 px-3 py-1.5 text-slate-700">Gray: shareable application layer</span></div>
  </div></section>;
}

export default function AboutPage() {
  const [live, setLive] = useState(null);
  useEffect(() => {
    Promise.all([localDataApi.pipelineCatalog(), localDataApi.vehicleMappings()])
      .then(([catalog, vehicles]) => setLive({ catalog: catalog.stats || {}, vehicles }))
      .catch(() => setLive(false));
  }, []);

  return <div className="space-y-6">
    <section className="overflow-hidden rounded-3xl bg-gradient-to-br from-slate-950 via-indigo-950 to-cyan-950 text-white shadow-panel"><div className="grid gap-8 px-6 py-9 sm:px-9 lg:grid-cols-[1.2fr_0.8fr] lg:items-center lg:py-12"><div><p className="flex items-center gap-2 text-xs font-black uppercase tracking-[0.2em] text-cyan-300"><Sparkles size={16} />Human + automated parts intelligence</p><h3 className="mt-3 max-w-3xl text-3xl font-black tracking-tight sm:text-4xl">Partmaster turns scattered catalog rows into evidence-backed parts data.</h3><p className="mt-4 max-w-2xl text-sm leading-7 text-slate-300 sm:text-base">It combines local processing, vehicle mappings, linked supplier evidence, optional AI research and human judgment. The goal is not to fill every blank—it is to create useful data without pretending uncertain facts are true.</p><div className="mt-6 flex flex-wrap gap-2"><span className="rounded-full bg-cyan-400 px-3 py-1.5 text-xs font-black text-slate-950">Fast local processing</span><span className="rounded-full bg-violet-400 px-3 py-1.5 text-xs font-black text-slate-950">Evidence before confidence</span><span className="rounded-full bg-emerald-400 px-3 py-1.5 text-xs font-black text-slate-950">Human control</span></div></div><div className="grid grid-cols-2 gap-3">{live && <><Metric label="Unique parts" value={live.catalog.unique_parts} /><Metric label="Product facts" value={live.catalog.attribute_facts} /><Metric label="Online verified" value={live.catalog.online_verified_parts} /><Metric label="Vehicle identities" value={live.vehicles.vehicles} /></>}{live === false && <div className="col-span-2 rounded-2xl border border-white/10 bg-white/[0.07] p-5"><HardDrive size={22} className="text-cyan-300" /><p className="mt-3 font-bold">The guide works anywhere.</p><p className="mt-1 text-sm leading-6 text-slate-300">Start the local worker to display live catalog totals here.</p></div>}</div></div></section>

    <SystemSchematic />

    <section className="rounded-3xl border border-slate-200 bg-white p-5 shadow-panel sm:p-7"><div className="max-w-3xl"><p className="text-xs font-black uppercase tracking-[0.16em] text-brand-700">Where enrichment comes from</p><h3 className="mt-2 text-2xl font-black tracking-tight">Six source layers, each with a different job</h3><p className="mt-2 text-sm leading-6 text-slate-600">A scraped description, an exact ePID mapping, an online catalog confirmation and a human approval do not carry the same meaning—so Partmaster keeps their origin visible.</p></div><div className="mt-6 grid gap-4 md:grid-cols-2 xl:grid-cols-3">{SOURCES.map(([Icon, tone, title, names, contribution, rule]) => <article key={title} className="rounded-2xl border border-slate-200 p-5"><span className={`grid h-11 w-11 place-items-center rounded-xl ring-1 ${tone}`}>{createElement(Icon, { size: 21 })}</span><h4 className="mt-4 font-black text-slate-900">{title}</h4><p className="mt-1 text-xs font-bold leading-5 text-slate-500">{names}</p><p className="mt-3 text-sm leading-6 text-slate-700">{contribution}</p><p className="mt-3 rounded-xl bg-slate-50 px-3 py-2.5 text-xs font-semibold leading-5 text-slate-600">{rule}</p></article>)}</div></section>

    <section className="overflow-hidden rounded-3xl border border-slate-200 bg-white shadow-panel"><header className="border-b border-slate-200 bg-gradient-to-r from-blue-50 to-violet-50 px-5 py-5 sm:px-7"><p className="text-xs font-black uppercase tracking-[0.16em] text-brand-700">The process</p><h3 className="mt-2 text-2xl font-black">From raw CSV to trusted output</h3></header><div className="grid md:grid-cols-2 xl:grid-cols-3">{STEPS.map(([number, title, detail]) => <article key={number} className="border-b border-slate-200 p-5 last:border-b-0 md:border-r md:[&:nth-child(2n)]:border-r-0 xl:[&:nth-child(2n)]:border-r xl:[&:nth-child(3n)]:border-r-0"><div className="flex gap-4"><span className="grid h-9 w-9 shrink-0 place-items-center rounded-xl bg-brand-600 text-sm font-black text-white">{number}</span><div><h4 className="font-black">{title}</h4><p className="mt-1 text-sm leading-6 text-slate-600">{detail}</p></div></div></article>)}</div></section>

    <div className="grid gap-6 lg:grid-cols-2"><section className="rounded-3xl border border-emerald-200 bg-emerald-50/60 p-5 sm:p-7"><div className="flex items-start gap-3"><span className="grid h-11 w-11 shrink-0 place-items-center rounded-xl bg-emerald-600 text-white"><SearchCheck size={21} /></span><div><h3 className="text-xl font-black text-emerald-950">What enrichment can add</h3><p className="mt-1 text-sm leading-6 text-emerald-800">Fields are category-aware: mirror equipment belongs to mirrors, thread size to hardware, and motorcycle type to vehicle fitment.</p></div></div><div className="mt-5 flex flex-wrap gap-2">{FIELDS.map((field) => <span key={field} className="rounded-full border border-emerald-200 bg-white px-3 py-1.5 text-xs font-bold text-emerald-800">{field}</span>)}</div></section><section className="rounded-3xl border border-amber-200 bg-amber-50/60 p-5 sm:p-7"><div className="flex items-start gap-3"><span className="grid h-11 w-11 shrink-0 place-items-center rounded-xl bg-amber-500 text-slate-950"><ShieldCheck size={21} /></span><div><h3 className="text-xl font-black text-amber-950">What Partmaster refuses to do</h3><p className="mt-1 text-sm leading-6 text-amber-900">Unknown is a valid quality state. The system protects the master instead of filling blanks with plausible guesses.</p></div></div><ul className="mt-5 space-y-3">{["It does not treat similar-looking OEM numbers as interchangeable.", "It does not infer heated, blind-spot, camera or other equipment without evidence.", "It does not merge parts across manufacturers.", "It does not overwrite richer facts with weaker online results.", "It does not publish conflicts silently; they go to human review."].map((item) => <li key={item} className="flex gap-3 text-sm leading-6 text-amber-950"><CheckCircle2 className="mt-0.5 shrink-0 text-amber-600" size={18} />{item}</li>)}</ul></section></div>

    <section className="rounded-3xl border border-slate-200 bg-white p-5 shadow-panel sm:p-7"><div className="flex items-start gap-3"><span className="grid h-11 w-11 shrink-0 place-items-center rounded-xl bg-slate-900 text-white"><Link2 size={20} /></span><div><h3 className="text-xl font-black">Where the data lives</h3><p className="mt-1 text-sm leading-6 text-slate-600">The split design makes a large catalog practical without cloud bandwidth for tens of millions of rows.</p></div></div><div className="mt-5 grid gap-4 md:grid-cols-2"><article className="rounded-2xl border border-slate-200 bg-slate-50 p-5"><p className="flex items-center gap-2 font-black"><HardDrive size={18} className="text-brand-700" />This Mac</p><p className="mt-2 text-sm leading-6 text-slate-600">Raw CSVs, MPSOV, DuckDB, background jobs, web-page cache and master CSV exports stay inside <span className="font-mono text-xs">partmaster/local_data</span>.</p></article><article className="rounded-2xl border border-slate-200 bg-slate-50 p-5"><p className="flex items-center gap-2 font-black"><GitBranch size={18} className="text-brand-700" />GitHub</p><p className="mt-2 text-sm leading-6 text-slate-600">The team-facing application, workflow code and lightweight reviewed records can be shared. GitHub Pages cannot directly read the Mac’s private files.</p></article></div></section>
  </div>;
}
