import { BarChart3, ChevronLeft, ChevronRight, Database, ExternalLink, HardDrive, LoaderCircle, Search, ShieldCheck, SlidersHorizontal } from "lucide-react";
import { useCallback, useEffect, useMemo, useState } from "react";
import { localDataApi } from "../utils/localDataApi.js";

const INITIAL_QUERY = { q: "", manufacturer: "", family: "", onlineStatus: "", factStatus: "", sort: "occurrences", direction: "desc", page: 1, pageSize: 50 };
const LOCAL_URL = "http://127.0.0.1:5173/partmaster/";

function number(value) { return Number(value || 0).toLocaleString(); }
function percent(value, total) { return Number(total) ? `${Math.round((Number(value || 0) / Number(total)) * 100)}%` : "0%"; }
function parseAttributes(value) { try { return Object.entries(JSON.parse(value || "{}")); } catch { return []; } }

function MetricCard({ label, value, detail, tone = "text-slate-950" }) {
  return <article className="rounded-2xl border border-slate-200 bg-white p-4 shadow-sm"><p className="text-[11px] font-black uppercase tracking-wide text-slate-500">{label}</p><p className={`mt-2 text-2xl font-black ${tone}`}>{number(value)}</p><p className="mt-1 text-xs leading-5 text-slate-500">{detail}</p></article>;
}

function Bars({ title, subtitle, rows, valueKey = "parts", accent = "bg-brand-500" }) {
  const max = Math.max(...(rows || []).map((row) => Number(row[valueKey] || 0)), 1);
  return <section className="rounded-3xl border border-slate-200 bg-white p-5 shadow-panel sm:p-6"><div className="flex items-start gap-3"><span className="grid h-10 w-10 shrink-0 place-items-center rounded-xl bg-brand-50 text-brand-700"><BarChart3 size={19} /></span><div><h3 className="font-black">{title}</h3><p className="mt-1 text-xs leading-5 text-slate-500">{subtitle}</p></div></div><div className="mt-5 space-y-3">{(rows || []).map((row) => <div key={row.label}><div className="mb-1 flex items-center justify-between gap-3 text-xs"><span className="truncate font-bold text-slate-700" title={row.label}>{row.label}</span><span className="font-black text-slate-900">{number(row[valueKey])}</span></div><div className="h-2 overflow-hidden rounded-full bg-slate-100"><div className={`h-full rounded-full ${accent}`} style={{ width: `${Math.max(1, (Number(row[valueKey]) / max) * 100)}%` }} /></div></div>)}</div></section>;
}

export default function MasterDataPage() {
  const [metrics, setMetrics] = useState(null);
  const [metricSource, setMetricSource] = useState("snapshot");
  const [connected, setConnected] = useState(null);
  const [filters, setFilters] = useState({ manufacturers: [], families: [] });
  const [query, setQuery] = useState(INITIAL_QUERY);
  const [catalog, setCatalog] = useState({ rows: [], total: 0, page: 1, pages: 1, pageSize: 50 });
  const [tableLoading, setTableLoading] = useState(false);
  const [tableError, setTableError] = useState("");

  useEffect(() => {
    fetch(`${import.meta.env.BASE_URL}data/master-metrics.json`).then((response) => response.json()).then(setMetrics).catch(() => null);
    const localHostname = ["127.0.0.1", "localhost", "::1"].includes(window.location.hostname);
    if (!localHostname) {
      setConnected(false);
      return;
    }
    Promise.all([localDataApi.masterDashboard(), localDataApi.masterCatalogFilters()])
      .then(([dashboard, availableFilters]) => { setMetrics(dashboard); setMetricSource("live"); setFilters(availableFilters); setConnected(true); })
      .catch(() => setConnected(false));
  }, []);

  const loadCatalog = useCallback(async (parameters) => {
    if (!connected) return;
    setTableLoading(true); setTableError("");
    try { setCatalog(await localDataApi.masterCatalog(parameters)); }
    catch (error) { setTableError(error.message); }
    finally { setTableLoading(false); }
  }, [connected]);

  useEffect(() => {
    if (!connected) return undefined;
    const timer = window.setTimeout(() => loadCatalog(query), 300);
    return () => window.clearTimeout(timer);
  }, [connected, loadCatalog, query]);

  const summary = metrics?.summary || {};
  const sourcePages = metrics?.source_pages || {};
  const visibleFamilies = useMemo(() => (metrics?.families || []).slice(0, 10), [metrics]);
  const updateQuery = (changes) => setQuery((current) => ({ ...current, ...changes, page: changes.page || 1 }));

  return <div className="space-y-6">
    <section className="overflow-hidden rounded-3xl bg-gradient-to-br from-slate-950 via-blue-950 to-emerald-950 text-white shadow-panel"><div className="flex flex-wrap items-start justify-between gap-5 px-6 py-7 sm:px-8"><div><p className="flex items-center gap-2 text-xs font-black uppercase tracking-[0.18em] text-cyan-300"><Database size={16} />Consolidated master catalog</p><h3 className="mt-2 text-3xl font-black tracking-tight">One searchable identity for every usable OEM part</h3><p className="mt-2 max-w-3xl text-sm leading-6 text-slate-300">Public metrics are lightweight and safe for GitHub Pages. The detailed catalog stays on this Mac and is queried page-by-page only when the local worker is connected.</p></div><div className="text-right"><div className={`rounded-full px-3 py-1.5 text-xs font-black ${metricSource === "live" ? "bg-emerald-400 text-emerald-950" : "bg-white/10 text-slate-200"}`}>{metricSource === "live" ? "Live local metrics" : "Published snapshot"}</div>{metrics?.generated_at && <p className="mt-2 text-[10px] font-semibold text-slate-400">Updated {new Date(metrics.generated_at).toLocaleString()}</p>}</div></div></section>

    {!metrics ? <div className="grid min-h-48 place-items-center rounded-3xl border border-slate-200 bg-white"><LoaderCircle className="animate-spin text-brand-600" size={28} /></div> : <>
      <section className="grid gap-3 sm:grid-cols-2 lg:grid-cols-4 xl:grid-cols-6"><MetricCard label="Unique parts" value={summary.unique_parts} detail="Manufacturer + normalized OEM identity" /><MetricCard label="Duplicates consolidated" value={summary.duplicate_occurrences} detail="Occurrences preserved as traceability" tone="text-brand-700" /><MetricCard label="Parts with facts" value={summary.parts_with_facts} detail={`${percent(summary.parts_with_facts, summary.unique_parts)} have extracted product attributes`} tone="text-emerald-700" /><MetricCard label="Product facts" value={summary.product_facts} detail="Category-aware structured attributes" /><MetricCard label="Online verified" value={summary.online_verified_parts} detail={`${percent(summary.online_verified_parts, summary.unique_parts)} supported by linked pages`} tone="text-cyan-700" /><MetricCard label="Missing descriptions" value={summary.missing_descriptions} detail="Held visible for repair—not guessed" tone="text-amber-700" /></section>
      <div className="grid gap-6 lg:grid-cols-2"><Bars title="Parts by manufacturer" subtitle="Deduplicated identities; public snapshot contains counts only." rows={metrics.manufacturers} /><Bars title="Largest part families" subtitle="The detailed rows and attribute JSON remain local." rows={visibleFamilies} accent="bg-emerald-500" /></div>
      <section className="grid gap-4 rounded-3xl border border-slate-200 bg-white p-5 shadow-panel sm:grid-cols-2 sm:p-6 lg:grid-cols-4"><div><p className="text-xs font-black uppercase tracking-wide text-slate-500">Source pages</p><p className="mt-1 text-2xl font-black">{number(sourcePages.source_pages)}</p></div><div><p className="text-xs font-black uppercase tracking-wide text-emerald-700">Processed pages</p><p className="mt-1 text-2xl font-black text-emerald-700">{number(sourcePages.processed_pages)}</p></div><div><p className="text-xs font-black uppercase tracking-wide text-cyan-700">High confidence</p><p className="mt-1 text-2xl font-black text-cyan-700">{number(summary.high_confidence_parts)}</p></div><div><p className="text-xs font-black uppercase tracking-wide text-amber-700">General/unclassified</p><p className="mt-1 text-2xl font-black text-amber-700">{number(summary.general_parts)}</p></div></section>
    </>}

    <section className="overflow-hidden rounded-3xl border border-slate-200 bg-white shadow-panel"><header className="flex flex-wrap items-start justify-between gap-4 border-b border-slate-200 bg-slate-50 px-5 py-5 sm:px-6"><div><p className="flex items-center gap-2 text-xs font-black uppercase tracking-wide text-brand-700"><HardDrive size={15} />Local-only detailed catalog</p><h3 className="mt-1 text-xl font-black">Search and filter master data</h3><p className="mt-1 text-sm text-slate-500">Only the current page—up to 200 records—is sent to the browser.</p></div>{connected && <span className="rounded-full bg-emerald-100 px-3 py-1.5 text-xs font-black text-emerald-800">Mac database connected</span>}</header>
      {connected === false ? <div className="grid gap-5 p-6 sm:p-8 lg:grid-cols-[1fr_auto] lg:items-center"><div><div className="flex items-center gap-3"><span className="grid h-11 w-11 place-items-center rounded-xl bg-amber-100 text-amber-700"><HardDrive size={21} /></span><div><h4 className="font-black text-slate-900">Detailed rows are intentionally local</h4><p className="mt-1 text-sm text-slate-600">Start <span className="font-mono text-xs">npm run dev:local</span> on the Mac to search all {number(summary.unique_parts)} parts.</p></div></div></div><a href={LOCAL_URL} className="inline-flex items-center justify-center gap-2 rounded-xl bg-brand-600 px-5 py-3 text-sm font-black text-white"><ExternalLink size={17} />Open local Master Data</a></div> : connected === null ? <div className="grid min-h-40 place-items-center"><LoaderCircle className="animate-spin text-brand-600" size={26} /></div> : <>
        <div className="grid gap-3 border-b border-slate-200 p-4 sm:p-5 lg:grid-cols-[minmax(16rem,2fr)_1fr_1fr_1fr_1fr]"><label className="text-[10px] font-black uppercase tracking-wide text-slate-500">Search<input value={query.q} onChange={(event) => updateQuery({ q: event.target.value })} placeholder="OEM number, description, family, attribute…" className="mt-1.5 w-full rounded-xl border border-slate-300 bg-white px-3 py-2.5 text-sm font-medium normal-case tracking-normal" /></label><label className="text-[10px] font-black uppercase tracking-wide text-slate-500">Manufacturer<select value={query.manufacturer} onChange={(event) => updateQuery({ manufacturer: event.target.value })} className="mt-1.5 w-full rounded-xl border border-slate-300 bg-white px-3 py-2.5 text-sm font-medium normal-case tracking-normal"><option value="">All makes</option>{filters.manufacturers.map((item) => <option key={item.value} value={item.value}>{item.value} ({number(item.count)})</option>)}</select></label><label className="text-[10px] font-black uppercase tracking-wide text-slate-500">Family<select value={query.family} onChange={(event) => updateQuery({ family: event.target.value })} className="mt-1.5 w-full rounded-xl border border-slate-300 bg-white px-3 py-2.5 text-sm font-medium normal-case tracking-normal"><option value="">All families</option>{filters.families.map((item) => <option key={item.value} value={item.value}>{item.value} ({number(item.count)})</option>)}</select></label><label className="text-[10px] font-black uppercase tracking-wide text-slate-500">Evidence<select value={query.onlineStatus} onChange={(event) => updateQuery({ onlineStatus: event.target.value })} className="mt-1.5 w-full rounded-xl border border-slate-300 bg-white px-3 py-2.5 text-sm font-medium normal-case tracking-normal"><option value="">All evidence</option><option value="verified">Online verified</option><option value="queued">Not yet verified</option></select></label><label className="text-[10px] font-black uppercase tracking-wide text-slate-500">Product facts<select value={query.factStatus} onChange={(event) => updateQuery({ factStatus: event.target.value })} className="mt-1.5 w-full rounded-xl border border-slate-300 bg-white px-3 py-2.5 text-sm font-medium normal-case tracking-normal"><option value="">All records</option><option value="with_facts">Has facts</option><option value="missing_facts">Missing facts</option></select></label></div>
        <div className="flex flex-wrap items-center justify-between gap-3 border-b border-slate-200 bg-white px-5 py-3 text-xs"><p className="font-semibold text-slate-600">{tableLoading ? "Searching…" : `${number(catalog.total)} matching parts`}</p><div className="flex items-center gap-2"><SlidersHorizontal size={15} className="text-slate-400" /><select value={`${query.sort}:${query.direction}`} onChange={(event) => { const [sort, direction] = event.target.value.split(":"); updateQuery({ sort, direction }); }} className="rounded-lg border border-slate-300 bg-white px-2.5 py-1.5 font-semibold"><option value="occurrences:desc">Most occurrences</option><option value="part_number:asc">OEM number A–Z</option><option value="manufacturer:asc">Manufacturer A–Z</option><option value="family:asc">Family A–Z</option><option value="facts:desc">Most product facts</option><option value="confidence:desc">Highest confidence</option><option value="updated:desc">Recently updated</option></select><select value={query.pageSize} onChange={(event) => updateQuery({ pageSize: Number(event.target.value) })} className="rounded-lg border border-slate-300 bg-white px-2.5 py-1.5 font-semibold"><option value="25">25 rows</option><option value="50">50 rows</option><option value="100">100 rows</option><option value="200">200 rows</option></select></div></div>
        {tableError && <div className="border-b border-red-200 bg-red-50 px-5 py-3 text-sm font-semibold text-red-800">{tableError}</div>}
        <div className="relative overflow-x-auto">{tableLoading && <div className="absolute inset-0 z-10 grid place-items-center bg-white/70"><LoaderCircle className="animate-spin text-brand-600" size={28} /></div>}<table className="min-w-full text-xs"><thead className="border-b border-slate-200 bg-slate-50 text-left uppercase tracking-wide text-slate-500"><tr>{["Manufacturer", "OEM part number", "Description / family", "Side / position", "Product facts", "Occurrences", "Evidence"].map((heading) => <th key={heading} className="whitespace-nowrap px-4 py-3">{heading}</th>)}</tr></thead><tbody className="divide-y divide-slate-100">{catalog.rows.map((part) => { const attributes = parseAttributes(part.extracted_attributes_json); return <tr key={part.part_key} className="align-top hover:bg-slate-50/70"><td className="whitespace-nowrap px-4 py-3 font-bold">{part.manufacturer}</td><td className="whitespace-nowrap px-4 py-3 font-mono font-black text-brand-700">{part.part_number}</td><td className="max-w-80 px-4 py-3"><p className="font-semibold text-slate-800">{part.description || "Description missing"}</p><p className="mt-1 text-[10px] font-bold uppercase tracking-wide text-violet-700">{part.family_name || "Unclassified"} · {(part.component_scope || "component").replaceAll("_", " ")}</p></td><td className="whitespace-nowrap px-4 py-3">{[part.side, part.position].filter((value) => value && value !== "Unknown").join(" · ") || "—"}</td><td className="max-w-72 px-4 py-3"><div className="flex flex-wrap gap-1">{attributes.length ? attributes.slice(0, 5).map(([key, value]) => <span key={key} className="rounded-md bg-emerald-50 px-1.5 py-1 font-semibold text-emerald-800">{key.replaceAll("_", " ")}: {value}</span>) : <span className="text-slate-400">No extracted facts</span>}</div></td><td className="px-4 py-3"><p className="font-black">{number(part.occurrence_count)}</p><p className="mt-1 text-[10px] text-slate-500">{number(part.dataset_count)} dataset(s)</p></td><td className="whitespace-nowrap px-4 py-3"><span className={`inline-flex items-center gap-1 rounded-full px-2 py-1 font-bold ${part.online_status === "verified" ? "bg-emerald-100 text-emerald-800" : "bg-slate-100 text-slate-600"}`}>{part.online_status === "verified" && <ShieldCheck size={12} />}{part.online_status.replaceAll("_", " ")}</span><p className="mt-1 text-[10px] font-bold text-slate-500">{Math.round(Number(part.confidence || 0) * 100)}% confidence</p></td></tr>; })}</tbody></table>{!catalog.rows.length && !tableLoading && <div className="grid min-h-44 place-items-center text-center"><div><Search className="mx-auto text-slate-300" size={28} /><p className="mt-2 text-sm font-bold text-slate-600">No master parts match these filters.</p></div></div>}</div>
        <footer className="flex flex-wrap items-center justify-between gap-3 border-t border-slate-200 bg-slate-50 px-5 py-4"><p className="text-xs font-semibold text-slate-500">Page {number(catalog.page)} of {number(catalog.pages)}</p><div className="flex gap-2"><button type="button" disabled={query.page <= 1 || tableLoading} onClick={() => updateQuery({ page: query.page - 1 })} className="inline-flex items-center gap-1 rounded-lg border border-slate-300 bg-white px-3 py-2 text-xs font-bold disabled:opacity-40"><ChevronLeft size={15} />Previous</button><button type="button" disabled={query.page >= catalog.pages || tableLoading} onClick={() => updateQuery({ page: query.page + 1 })} className="inline-flex items-center gap-1 rounded-lg border border-slate-300 bg-white px-3 py-2 text-xs font-bold disabled:opacity-40">Next<ChevronRight size={15} /></button></div></footer>
      </>}
    </section>
  </div>;
}
