export function candidateReviewValues(candidate) {
  return {
    partNumber: candidate.enriched_part_number || candidate.part_number_raw || "",
    description: candidate.enriched_description || candidate.description_raw || "",
    side: candidate.side || "Unknown",
    position: candidate.position || "",
    locationNotes: candidate.location_notes || "",
    familyName: candidate.family_name || "",
    componentScope: candidate.component_scope || "component",
    heatedState: candidate.heated_state || "unknown",
    autoDimmingState: candidate.auto_dimming_state || "unknown",
    powerFoldingState: candidate.power_folding_state || "unknown",
    memoryState: candidate.memory_state || "unknown",
    blindSpotState: candidate.blind_spot_state || "unknown",
    cameraState: candidate.camera_state || "unknown",
    turnSignalState: candidate.turn_signal_state || "unknown",
    connectorPins: candidate.connector_pins || "",
    requiredOptions: candidate.required_options || "",
    excludedOptions: candidate.excluded_options || "",
    variantSummary: candidate.variant_summary || "",
    fitmentExplanation: candidate.fitment_explanation || "",
    notes: candidate.decision_notes || "",
    evidenceUrl: candidate.evidence_url || candidate.source_url || "",
  };
}
